Make gdrush log executed commands, and exit non zero if any command failed.

diff --git a/bin/gdrush b/bin/gdrush
--- a/bin/gdrush
+++ b/bin/gdrush
@@ -16,8 +16,16 @@ test -e vendor/bin/drush || exit 1
 
 drush='vendor/bin/drush'
 
-$drush sa --format=list | grep $grep_pattern | xargs -I % echo "Running: drush % $@"; $drush % "$@"
-exit_code=$?
+exit_code=0
+$drush sa --format=list | grep $grep_pattern | while read -r alias; do
+    echo "Running: \"drush $alias $@\""
+    $drush $alias "$@"
+    temp_exit_code = $?
+    if [ $temp_exit_code -ne 0 ]; then
+        echo "ERROR: Command \"drush $alias $@\" failed"
+        exit_code=$temp_exit_code
+    fi
+done
 
 cd $directory
 exit $exit_code
